CREATE TABLE todo
(
    id     BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '메모 식별자',
    todo	    VARCHAR(2000)	NOT NULL COMMENT '할일',
    author	    VARCHAR(20)	NOT NULL COMMENT '작성자',
    pw	VARCHAR(10)	NOT NULL COMMENT '비밀번호',
    created	    DATETIME DEFAULT CURRENT_TIMESTAMP	NOT NULL COMMENT '작성일',
    modified	DATETIME DEFAULT CURRENT_TIMESTAMP	NOT NULL COMMENT '수정일'
);